### ISSUE TITLE
Workstation app update check pops up an error when connection times out

### ISSUE THREAD

**Issue by gsreynolds** [chef/chef-workstation-app#180]
## Description
When the Chef Workstation app attempts to connect to Fastly for the update check and times out - for example connections to Fastly CDN are blocked on a customer's network - the following popup appears.

![chef_ws_update_timeouts](https://user-images.githubusercontent.com/1533562/76524936-dae16a80-6462-11ea-9ef2-bd3a447fe639.png)

This is less than delightful as the user is unable to do anything about that. Auto-update checks should fail silently, or perhaps report the date of the last successful update check in the "About Chef Workstation" dialog instead.

## Chef Workstation Version
0.16.33

## Platform Version
Windows 10

**Comment by marcparadise** [comment]
Related:  https://files.slack.com/files-pri/T0M1PBN4E-F01509BBSP8/image.png
![image](https://user-images.githubusercontent.com/1130204/84412041-a6558a00-abdc-11ea-94e1-a54c53de62d3.png)


The message should only be displaying when the user has requested an update check from the menu, so that if it fails they're not left with no response. Unless the user has directly requested the check, no popup should be seen.
