### ISSUE TITLE
A JavaScript error occurred in the main process while opening workstation app

### ISSUE THREAD

**Issue by rishichawda** [chef/chef-workstation-app#289]
# Describe the problem
When trying to start the workstation app GUI on macOS, it shows this window and can't be removed from view:

<img width="488" alt="Screenshot 2021-02-09 at 11 45 35 PM" src="https://user-images.githubusercontent.com/26366288/107411263-5694dd00-6b34-11eb-943e-37b88202a7c9.png">

Expected: Workstation GUI is shown.

## Software Version
Chef Workstation version: 20.11.180
Operating system: macOS 10.15.5, Windows 10 Pro

## Replication Case
The profile that it is unable to find was added manually to `~/.chef/credentials,` used to upload policies, and then removed after it was no longer required. But knife was never reconfigured to use a different profile using the `knife config use-profile` command.

## Stacktrace
From the window:
```
at checkExecSyncError (child_process.js:630:11)
    at execFileSync (child_process.js:648:15)
    at func (electron/js2c/asar.js:140:31)
    at queryOhai (/Applications/Chef Workstation App.app/Contents/Resources/app.asar/src/helpers/chef_workstation.js:195:16)
    at Object.getPlatformInfo (/Applications/Chef Workstation App.app/Contents/Resources/app.asar/src/helpers/chef_workstation.js:177:12)
    at new OmnitruckUpdateChecker (/Applications/Chef Workstation App.app/Contents/Resources/app.asar/src/omnitruck-update-checker/omnitruck-update-checker.js:14:41)
    at new Main (/Applications/Chef Workstation App.app/Contents/Resources/app.asar/src/main.js:15:39)
    at Object.<anonymous> (/Applications/Chef Workstation App.app/Contents/Resources/app.asar/src/app.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
```

**Comment by PopPopDevOps** [comment]
We are experiencing the same issue

**Comment by SmishaM** [comment]
Please find the below discussion with @marcparadise 

It makes sense that we're using ohai to gather system data, becausae that will give us fields like 'platform' with values that we know omnitruck will accept.

However, we don't have control over what configuration errors/issues might exist. In the case of this issue, it seems like we've configured a default profile for chef that is no longer valid.

**Comment by SmishaM** [comment]
I think there are two things we can do here:

1) catch the exception and don't display an error to the user (this particular error will make no sense to the user, and they can't fix it based on what is shown anyway. This might require a conversation with Tim/product to figure out what we should do in this case - we can't just hide the errors forever, or customers won't be able to get update notifications.  This is part of a larger issue with how we handle errors in Workstation App.

2) include an empty config file and explicitly use it when launching ohai, like ohai -c /path/to/empty-config.rb.  That will prevent a broken user config from causing failures.  The only concern here is that a user might have disabled certain ohai plugins or otherwise configured ohai - and we won't be respecting that.   I don't think that's a huge issue (though it might cause very slow run time of ohai, it's all behind-the-scenes to the user); but this is probably another question for product to determine the right behavior.

**Comment by SmishaM** [comment]
@marcparadise @tas50 Please let me know what might be the best solution to handle this issue

**Comment by marcparadise** [comment]
If we did 'option 1', we would not be able to check for updates because the call to ohai failed; since that's one of the primary capabilities of the WSA we want to ensure it keeps working.   Wiith that in mind, let's go 'option 2' and force an empty ohai config.

**Comment by PopPopDevOps** [comment]
What is the whole workstation App Gui? All we need is kitchen, cookstyle, and whatever gems so that a cookbook can be written. Is anyone using an App with a GUI to create cookbooks?

**Comment by tas50** [comment]
@SmishaM @marcparadise do we have any idea why ohai is failing to run?

**Comment by PopPopDevOps** [comment]
We are finding that users without local admin are seeing this error. If we are planning on just using chef and knife commands should we do the headless install instead? I need to get my users on the new version so we are ready for the chef client upgrades in the near future to remain on a supported platform

**Comment by nikhil2611** [comment]
This issue is no longer coming in the updated versions. Closing the issue, feel free to reopen if you face this again.
